#Crear BD previa llamada "demo"
spring.application.name=demo
spring.datasource.url=jdbc:mysql://demo-mysql:3306/demo
spring.datasource.username=root
# Colocamos la nueva contraseña segura que guardamos en MySQL
spring.datasource.password=Abcd.1234#

# Spring crea las tablas automáticamente la primera vez
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
